services:
  insy-mysql:
    container_name: insy-mysql
    image: mysql:8.0.26
    ports:
      - "3398:3306"
    volumes:
      - insy-mysql-vol:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql

volumes:
  insy-mysql-vol:
    name: insy-mysql
